#!/bin/bash
clear
a='\033[31;1m'
b='\033[32;1m'
c='\033[33;1m'
d='\033[34;1m'
e='\033[35;1m'
f='\033[36;1m'
g='\033[37;1m'

trap ctrl_c INT
ctrl_c(){
clear
echo -e "$a[$g!$a]$g CTRL+C Terdeteksi"
sleep 0.5
echo -e "$a[$g!$a]$g Password untuk keluar"
echo -e "$a[$g!$a]$g Jika salah akan error"
read -p "Password : " pw
if [ $pw = ShaDoW ]
then
sleep 1
echo -e "$b[$g+$b]$g Terima kasih telah menggunakan tools SBI-BDW"
exit
else
echo -e "$a[$g!$a]$g Password salah"
sleep 3
while [ true ]
do
echo -e "\033[42;1mShaDoW BlooD InDoNeSiA || Error : 404 Not found || BOOM !!"
sleep 0.000000000000000000000000000000000000000000000000000000000000000000001
echo -e "\033[46;1mWe Always Together Because of Family || Error :404 Not found"
sleep 0.000000000000000000000000000000000000000000000000000000000000000000001
done
fi
}

echo -e "$b Author :$g <[SBI_01]"
echo -e "$b Tools  :$g Brute Webdav"
echo -e "$b Team   :$g ShaDoW BlooD InDoNeSiA$g"
sleep 0.7
echo -e "___
\  \::::::::
 \  \::::::::
  \  \::::::::
   \  \::::::::
    \  \::::::::
     \  \::::::::
      \  \::::::::
       \  \::::::::
        \  \::::::::
        /  /::::::::
       /  /::::::::
      /  /::::::::
     /  /::::::::
    /  /::::::::
   /  /::::::::$b ________________________$g
  /  /:::::::: $b|________________________|$g
 /  /::::::::
/__/::::::::$b"
cat mod
sleep 0.5
echo ""
echo -e " $b[\033[37;1m01$b]$g Brute Deface"
echo -e " $b[\033[37;1m02$b]$g Brute Upload"
echo -e " $b[\033[37;1m03$b]$g Help"
echo -e " $b[\033[37;1m04$b]$g Info Tools"
echo -e " $b[\033[37;1m05$b]$g Keluar"
read -p " [Pilihan]=>> " pilih

if [ $pilih = 01 ] || [ $pilih = 1 ]
then
cd module
sleep 0.5
bash BDW
sleep 1
cd ..
echo ''
echo -e " Keluar??"
read -p " [Y/N]=>> " out
fi

if [ $pilih = 02 ] || [ $pilih = 2 ]
then
cd module
sleep 0.5
bash BUW
sleep 1
cd ..
echo ''
echo -e " Keluar??"
read -p " [Y/N]=>> " out
fi
if [ $pilih = 03 ] || [ $pilih = 3 ]
then
sleep 0.5
echo -e " $b-$g>$b Webdav$g merupakan deface dengan poc termudah"
echo -e "    Karena biasanya hanya memakai curl di linux"
echo -e "$b    Enter$g untuk lanjut"
read enter
echo -e " $b-$g>$b BDW$g singkatan dari$b Brute Deface Webdav$g"
echo -e "    Adalah Deface web melalui target banyak"
echo -e "    namun hanya memakai satu script deface"
echo -e "$b    Enter$g untuk lanjut"
read enter
echo -e " $b-$g>$b BUW$g singkatan dari$b Brute Upload Webdav$g"
echo -e "    Adalah Deface web melalui upload file banyak"
echo -e "    namun hanya memiliki satu target web"
echo -e "$b    Enter$g untuk lanjut"
read enter
echo -e " $b-$g>$b Alamat file$g adalah alamat penyimpanan"
echo -e "    file yang ingin diupload"
echo -e " $b   Contoh :$g /sdcard"
echo -e "$b    Enter$g untuk lanjut"
read enter
echo -e " $b-$g>$b Nama file$g adalah nama dari file/script"
echo -e "    yang ingin diupload"
echo -e " $b   Contoh :$g index.html"
echo -e "$b    Enter$g untuk lanjut"
read enter
echo -e " $b-$g>$b Target$g adalah link web"
echo -e "    yang ingin di$b Deafce"
echo -e " $b   Catatan :$g Tanpa http://"
echo -e " $b   Contoh :$g apparelworld.org"
echo -e "$b    Enter$g untuk lanjut"
read enter
echo -e " $b-$g>$b Count$g adalah$b JUMLAH$g yang ditentukan"
echo -e "    yang dibagi menjadi dua"
echo -e "  $g-$b Target :$g Jumlah 1-35"
echo -e "  $g-$b Script :$g Jumlah 1-15"
echo -e "$b    Enter$g untuk lanjut"
read enter
echo -e " Terima kasih telah membaca Help"
sleep 5
bash index
fi

if [ $pilih = 04 ] || [ $pilih = 4 ]
then
echo -e "$b Author   :$g <[SBI_01]"
sleep 0.5
echo -e "$b Name     :$g SBI-BW"
sleep 0.5
echo -e "$b Team     :$g ShaDoW BlooD InDoNeSiA"
sleep 0.5
echo -e "$b GitHub   :$g https://github.com/SBI-Team/SBI-BW"
sleep 0.5
echo -e "$b Date     :$g 25 Maret 2019"
sleep 0.5
echo -e "$b Version  :$g 1.0"
sleep 0.5
echo -e "$b Kegunaan :$g Deface Web yang vuln curl/webdav"
sleep 0.5
echo -e " Terima kasih telah membaca Info Tools"
echo -e " Silahkan tekan$b Enter"
read enter
bash index
fi

if [ $pilih = 05 ] || [ $pilih = 5 ]
then
echo -e " Yakin ingin$b keluar$g??"
read -p " [Y/N]=>> " out
sleep 1
fi

if [ $out = Y ] || [ $out = y ]
then
echo -e " Terima kasih telah menggunakan tools SBI-BW"
sleep 3
exit
fi

if [ $out = N ] || [ $out = n ]
then
echo -e " Selamat datang kembali"
sleep 2
bash index
fi
