#!/bin/bash
clear
a='\033[31;1m'
b='\033[32;1m'
c='\033[33;1m'
d='\033[34;1m'
e='\033[35;1m'
f='\033[36;1m'
g='\033[37;1m'

echo -e "$b"
cat bdw.txt
sleep 0.5
echo -e "$g"
read -p " Alamat file : " almt
read -p " Nama file : " nm
read -p " Count Target : " jml

if [ $jml = 01 ] || [ $jml = 1 ]
then
read -p " Target ke-1 : " tg1
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
fi

if [ $jml = 02 ] || [ $jml = 2 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
fi

if [ $jml = 03 ] || [ $jml = 3 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
fi

if [ $jml = 04 ] || [ $jml = 4 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
fi

if [ $jml = 05 ] || [ $jml = 5 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
fi

if [ $jml = 06 ] || [ $jml = 6 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
fi

if [ $jml = 07 ] || [ $jml = 7 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
fi

if [ $jml = 08 ] || [ $jml = 8 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
fi

if [ $jml = 09 ] || [ $jml = 9 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
fi

if [ $jml = 10 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
fi

if [ $jml = 11 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
fi

if [ $jml = 12 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
fi

if [ $jml = 13 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
fi

if [ $jml = 14 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
fi

if [ $jml = 15 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
fi

if [ $jml = 16 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
fi

if [ $jml = 17 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
fi

if [ $jml = 18 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
fi

if [ $jml = 19 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
fi

if [ $jml = 20 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
fi

if [ $jml = 21 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
fi

if [ $jml = 22 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
fi

if [ $jml = 23 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
fi

if [ $jml = 24 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg24
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
fi

if [ $jml = 25 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg24
curl -T $almt/$nm $tg25
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
fi

if [ $jml = 26 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
read -p " Target ke-26 : " tg26
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg24
curl -T $almt/$nm $tg25
curl -T $almt/$nm $tg26
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
echo -e " $b[\033[37;1m26$b]$g Cek : $tg26/$nm"
fi

if [ $jml = 27 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
read -p " Target ke-26 : " tg26
read -p " Target ke-27 : " tg27
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg24
curl -T $almt/$nm $tg25
curl -T $almt/$nm $tg26
curl -T $almt/$nm $tg27
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
echo -e " $b[\033[37;1m26$b]$g Cek : $tg26/$nm"
echo -e " $b[\033[37;1m27$b]$g Cek : $tg27/$nm"
fi

if [ $jml = 28 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
read -p " Target ke-26 : " tg26
read -p " Target ke-27 : " tg27
read -p " Target ke-28 : " tg28
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg24
curl -T $almt/$nm $tg25
curl -T $almt/$nm $tg26
curl -T $almt/$nm $tg27
curl -T $almt/$nm $tg28
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
echo -e " $b[\033[37;1m26$b]$g Cek : $tg26/$nm"
echo -e " $b[\033[37;1m27$b]$g Cek : $tg27/$nm"
echo -e " $b[\033[37;1m28$b]$g Cek : $tg28/$nm"
fi

if [ $jml = 29 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
read -p " Target ke-26 : " tg26
read -p " Target ke-27 : " tg27
read -p " Target ke-28 : " tg28
read -p " Target ke-29 : " tg29
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg24
curl -T $almt/$nm $tg25
curl -T $almt/$nm $tg26
curl -T $almt/$nm $tg27
curl -T $almt/$nm $tg28
curl -T $almt/$nm $tg29
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
echo -e " $b[\033[37;1m26$b]$g Cek : $tg26/$nm"
echo -e " $b[\033[37;1m27$b]$g Cek : $tg27/$nm"
echo -e " $b[\033[37;1m28$b]$g Cek : $tg28/$nm"
echo -e " $b[\033[37;1m29$b]$g Cek : $tg29/$nm"
fi

if [ $jml = 30 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
read -p " Target ke-26 : " tg26
read -p " Target ke-27 : " tg27
read -p " Target ke-28 : " tg28
read -p " Target ke-29 : " tg29
read -p " Target ke-30 : " tg30
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg24
curl -T $almt/$nm $tg25
curl -T $almt/$nm $tg26
curl -T $almt/$nm $tg27
curl -T $almt/$nm $tg28
curl -T $almt/$nm $tg29
curl -T $almt/$nm $tg30
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
echo -e " $b[\033[37;1m26$b]$g Cek : $tg26/$nm"
echo -e " $b[\033[37;1m27$b]$g Cek : $tg27/$nm"
echo -e " $b[\033[37;1m28$b]$g Cek : $tg28/$nm"
echo -e " $b[\033[37;1m29$b]$g Cek : $tg29/$nm"
echo -e " $b[\033[37;1m30$b]$g Cek : $tg30/$nm"
fi

if [ $jml = 31 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
read -p " Target ke-26 : " tg26
read -p " Target ke-27 : " tg27
read -p " Target ke-28 : " tg28
read -p " Target ke-29 : " tg29
read -p " Target ke-30 : " tg30
read -p " Target ke-31 : " tg31
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg25
curl -T $almt/$nm $tg26
curl -T $almt/$nm $tg27
curl -T $almt/$nm $tg28
curl -T $almt/$nm $tg29
curl -T $almt/$nm $tg30
curl -T $almt/$nm $tg31
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
echo -e " $b[\033[37;1m26$b]$g Cek : $tg26/$nm"
echo -e " $b[\033[37;1m27$b]$g Cek : $tg27/$nm"
echo -e " $b[\033[37;1m28$b]$g Cek : $tg28/$nm"
echo -e " $b[\033[37;1m29$b]$g Cek : $tg29/$nm"
echo -e " $b[\033[37;1m30$b]$g Cek : $tg30/$nm"
echo -e " $b[\033[37;1m31$b]$g Cek : $tg31/$nm"
fi

if [ $jml = 32 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
read -p " Target ke-26 : " tg26
read -p " Target ke-27 : " tg27
read -p " Target ke-28 : " tg28
read -p " Target ke-29 : " tg29
read -p " Target ke-30 : " tg30
read -p " Target ke-31 : " tg31
read -p " Target ke-32 : " tg32
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg25
curl -T $almt/$nm $tg26
curl -T $almt/$nm $tg27
curl -T $almt/$nm $tg28
curl -T $almt/$nm $tg29
curl -T $almt/$nm $tg30
curl -T $almt/$nm $tg31
curl -T $almt/$nm $tg32
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
echo -e " $b[\033[37;1m26$b]$g Cek : $tg26/$nm"
echo -e " $b[\033[37;1m27$b]$g Cek : $tg27/$nm"
echo -e " $b[\033[37;1m28$b]$g Cek : $tg28/$nm"
echo -e " $b[\033[37;1m29$b]$g Cek : $tg29/$nm"
echo -e " $b[\033[37;1m30$b]$g Cek : $tg30/$nm"
echo -e " $b[\033[37;1m31$b]$g Cek : $tg31/$nm"
echo -e " $b[\033[37;1m32$b]$g Cek : $tg32/$nm"
fi

if [ $jml = 33 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
read -p " Target ke-26 : " tg26
read -p " Target ke-27 : " tg27
read -p " Target ke-28 : " tg28
read -p " Target ke-29 : " tg29
read -p " Target ke-30 : " tg30
read -p " Target ke-31 : " tg31
read -p " Target ke-32 : " tg32
read -p " Target ke-33 : " tg33
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg25
curl -T $almt/$nm $tg26
curl -T $almt/$nm $tg27
curl -T $almt/$nm $tg28
curl -T $almt/$nm $tg29
curl -T $almt/$nm $tg30
curl -T $almt/$nm $tg31
curl -T $almt/$nm $tg32
curl -T $almt/$nm $tg33
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
echo -e " $b[\033[37;1m26$b]$g Cek : $tg26/$nm"
echo -e " $b[\033[37;1m27$b]$g Cek : $tg27/$nm"
echo -e " $b[\033[37;1m28$b]$g Cek : $tg28/$nm"
echo -e " $b[\033[37;1m29$b]$g Cek : $tg29/$nm"
echo -e " $b[\033[37;1m30$b]$g Cek : $tg30/$nm"
echo -e " $b[\033[37;1m31$b]$g Cek : $tg31/$nm"
echo -e " $b[\033[37;1m32$b]$g Cek : $tg32/$nm"
echo -e " $b[\033[37;1m33$b]$g Cek : $tg33/$nm"
fi

if [ $jml = 34 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
read -p " Target ke-26 : " tg26
read -p " Target ke-27 : " tg27
read -p " Target ke-28 : " tg28
read -p " Target ke-29 : " tg29
read -p " Target ke-30 : " tg30
read -p " Target ke-31 : " tg31
read -p " Target ke-32 : " tg32
read -p " Target ke-33 : " tg33
read -p " Target ke-34 : " tg34
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg25
curl -T $almt/$nm $tg26
curl -T $almt/$nm $tg27
curl -T $almt/$nm $tg28
curl -T $almt/$nm $tg29
curl -T $almt/$nm $tg30
curl -T $almt/$nm $tg31
curl -T $almt/$nm $tg32
curl -T $almt/$nm $tg33
curl -T $almt/$nm $tg34
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
echo -e " $b[\033[37;1m26$b]$g Cek : $tg26/$nm"
echo -e " $b[\033[37;1m27$b]$g Cek : $tg27/$nm"
echo -e " $b[\033[37;1m28$b]$g Cek : $tg28/$nm"
echo -e " $b[\033[37;1m29$b]$g Cek : $tg29/$nm"
echo -e " $b[\033[37;1m30$b]$g Cek : $tg30/$nm"
echo -e " $b[\033[37;1m31$b]$g Cek : $tg31/$nm"
echo -e " $b[\033[37;1m32$b]$g Cek : $tg32/$nm"
echo -e " $b[\033[37;1m33$b]$g Cek : $tg33/$nm"
echo -e " $b[\033[37;1m34$b]$g Cek : $tg34/$nm"
fi

if [ $jml = 35 ]
then
read -p " Target ke-1 : " tg1
read -p " Target ke-2 : " tg2
read -p " Target ke-3 : " tg3
read -p " Target ke-4 : " tg4
read -p " Target ke-5 : " tg5
read -p " Target ke-6 : " tg6
read -p " Target ke-7 : " tg7
read -p " Target ke-8 : " tg8
read -p " Target ke-9 : " tg9
read -p " Target ke-10 : " tg10
read -p " Target ke-11 : " tg11
read -p " Target ke-12 : " tg12
read -p " Target ke-13 : " tg13
read -p " Target ke-14 : " tg14
read -p " Target ke-15 : " tg15
read -p " Target ke-16 : " tg16
read -p " Target ke-17 : " tg17
read -p " Target ke-18 : " tg18
read -p " Target ke-19 : " tg19
read -p " Target ke-20 : " tg20
read -p " Target ke-21 : " tg21
read -p " Target ke-22 : " tg22
read -p " Target ke-23 : " tg23
read -p " Target ke-24 : " tg24
read -p " Target ke-25 : " tg25
read -p " Target ke-26 : " tg26
read -p " Target ke-27 : " tg27
read -p " Target ke-28 : " tg28
read -p " Target ke-29 : " tg29
read -p " Target ke-30 : " tg30
read -p " Target ke-31 : " tg31
read -p " Target ke-32 : " tg32
read -p " Target ke-33 : " tg33
read -p " Target ke-34 : " tg34
read -p " Target ke-35 : " tg35
echo -e " $b[$g#$b]$g Processing..."
curl -T $almt/$nm $tg1
curl -T $almt/$nm $tg2
curl -T $almt/$nm $tg3
curl -T $almt/$nm $tg4
curl -T $almt/$nm $tg5
curl -T $almt/$nm $tg6
curl -T $almt/$nm $tg7
curl -T $almt/$nm $tg8
curl -T $almt/$nm $tg9
curl -T $almt/$nm $tg10
curl -T $almt/$nm $tg11
curl -T $almt/$nm $tg12
curl -T $almt/$nm $tg13
curl -T $almt/$nm $tg14
curl -T $almt/$nm $tg15
curl -T $almt/$nm $tg16
curl -T $almt/$nm $tg17
curl -T $almt/$nm $tg18
curl -T $almt/$nm $tg19
curl -T $almt/$nm $tg20
curl -T $almt/$nm $tg21
curl -T $almt/$nm $tg22
curl -T $almt/$nm $tg23
curl -T $almt/$nm $tg25
curl -T $almt/$nm $tg26
curl -T $almt/$nm $tg27
curl -T $almt/$nm $tg28
curl -T $almt/$nm $tg29
curl -T $almt/$nm $tg30
curl -T $almt/$nm $tg31
curl -T $almt/$nm $tg32
curl -T $almt/$nm $tg33
curl -T $almt/$nm $tg34
curl -T $almt/$nm $tg35
echo -e " $b[$g+$b]$g Done..."
echo -e " $b[\033[37;1m01$b]$g Cek : $tg1/$nm"
echo -e " $b[\033[37;1m02$b]$g Cek : $tg2/$nm"
echo -e " $b[\033[37;1m03$b]$g Cek : $tg3/$nm"
echo -e " $b[\033[37;1m04$b]$g Cek : $tg4/$nm"
echo -e " $b[\033[37;1m05$b]$g Cek : $tg5/$nm"
echo -e " $b[\033[37;1m06$b]$g Cek : $tg6/$nm"
echo -e " $b[\033[37;1m07$b]$g Cek : $tg7/$nm"
echo -e " $b[\033[37;1m08$b]$g Cek : $tg8/$nm"
echo -e " $b[\033[37;1m09$b]$g Cek : $tg9/$nm"
echo -e " $b[\033[37;1m10$b]$g Cek : $tg10/$nm"
echo -e " $b[\033[37;1m11$b]$g Cek : $tg11/$nm"
echo -e " $b[\033[37;1m12$b]$g Cek : $tg12/$nm"
echo -e " $b[\033[37;1m13$b]$g Cek : $tg13/$nm"
echo -e " $b[\033[37;1m14$b]$g Cek : $tg14/$nm"
echo -e " $b[\033[37;1m15$b]$g Cek : $tg15/$nm"
echo -e " $b[\033[37;1m16$b]$g Cek : $tg16/$nm"
echo -e " $b[\033[37;1m17$b]$g Cek : $tg17/$nm"
echo -e " $b[\033[37;1m18$b]$g Cek : $tg18/$nm"
echo -e " $b[\033[37;1m19$b]$g Cek : $tg19/$nm"
echo -e " $b[\033[37;1m20$b]$g Cek : $tg20/$nm"
echo -e " $b[\033[37;1m21$b]$g Cek : $tg21/$nm"
echo -e " $b[\033[37;1m22$b]$g Cek : $tg22/$nm"
echo -e " $b[\033[37;1m23$b]$g Cek : $tg23/$nm"
echo -e " $b[\033[37;1m24$b]$g Cek : $tg24/$nm"
echo -e " $b[\033[37;1m25$b]$g Cek : $tg25/$nm"
echo -e " $b[\033[37;1m26$b]$g Cek : $tg26/$nm"
echo -e " $b[\033[37;1m27$b]$g Cek : $tg27/$nm"
echo -e " $b[\033[37;1m28$b]$g Cek : $tg28/$nm"
echo -e " $b[\033[37;1m29$b]$g Cek : $tg29/$nm"
echo -e " $b[\033[37;1m30$b]$g Cek : $tg30/$nm"
echo -e " $b[\033[37;1m31$b]$g Cek : $tg31/$nm"
echo -e " $b[\033[37;1m32$b]$g Cek : $tg32/$nm"
echo -e " $b[\033[37;1m33$b]$g Cek : $tg33/$nm"
echo -e " $b[\033[37;1m34$b]$g Cek : $tg34/$nm"
echo -e " $b[\033[37;1m35$b]$g Cek : $tg35/$nm"
fi
